### ISSUE TITLE
hi what is exact solidity compiler version for contracts

### ISSUE THREAD

**Issue by gsngsn123** [tudor199/Web3Arbitrage#1]
hi  really greate work learn a lot from ur work thank and i have 2 doubts please help me

1: what is exact solidity version for contract deployment

2. what is the status in logs.txt example below

STATUS
WMATIC : 0.000000000000000000
WETH   : 0.000000000000000000
USDC   : 0.000000000000000000
DAI    : 0.000000000000000000
ETH    : 17.807890175440267200
Time: 15-03-2022 at 21:48:58

**Comment by tudor199** [comment]
Nice to hear that, regarding your questions
1: The compile version is 0.8.12
2: The logs is giving you information about the program (balances, full tx of orders, arbitrage opportunities, and exceptions), the one that you send is a balance info, it will list you all balances of your sideTokens defined in configurations.py and the blockchain's coin as ETH (for example on Polygon MATIC is the blockchain's coin so you can find your balance of MATIC in ETH row)

**Comment by gsngsn123** [comment]
thank you for quick reply may what is the minimum possible profit can set for oppurtinities

**Comment by tudor199** [comment]
You can set the minimum profit as much and as less as you want in configuration.py at minAmount for each sideToken.

**Comment by gsngsn123** [comment]
finally made transaction but Fail with error 'ArbitrageExecutor: Initial check failed!'

may i know what is reason

iam using alchemy is it ok and is thare any solutions escape above error

**Comment by tudor199** [comment]
This error will appear when there is no longer an arbitrage opportunity for the given pair, basically it fails at sell(buy(inputAmount)) >= inputAmount + minPorfit

**Comment by gsngsn123** [comment]
iam host alchemy is it ok or any better host providers or thare

**Comment by tudor199** [comment]
I don`t know which provider is the best.
