### ISSUE TITLE
How does the profit calculation logic work?

### ISSUE THREAD

**Issue by nervodatascience** [tudor199/Web3Arbitrage#15]
I'm trying to implement the profit calculation to keep the transaction fee discounted from the profit ... how does the profit calculation work

**Comment by tudor199** [comment]
The profit you are receiving is [here](https://github.com/tudor199/Web3Arbitrage/blob/main/group/group.py#L65) (amountOut - amountIn), you can check the price of that token (side tokens) and based on that you can calculate the maximum transaction fee with estimate_gas function by web3.py

**Comment by nervodatascience** [comment]
thanks , but now the transaction is failing , any idea how to implement the batch calculation ?
