### ISSUE TITLE
hi tried below line to reduce failure transactions but solidity errorDeclarationError: Undeclared identifier.

### ISSUE THREAD

**Issue by gsngsn123** [tudor199/Web3Arbitrage#3]
hi tried below line to reduce failure transactions but solidity errorDeclarationError: Undeclared identifier.
can u help me how to edit this code in excecutor solidity contract line 80

require(finalAmount >= initialAmount + minAmount, "ArbitrageExecutor: Initial check failed!");   

or is it possible  profit= grater than or less than 

i replace minAmount instead of profit can u pls guide me how do this

**Comment by tudor199** [comment]
This line is there to avoid consuming gas if the opportunity is not available anymore.

**Comment by gsngsn123** [comment]
.
