### ISSUE TITLE
Fail with error 'UniswapV2: INSUFFICIENT_INPUT_AMOUNT' and Fail with error 'UniswapV2: TRANSFER_FAILED'

### ISSUE THREAD

**Issue by gsngsn123** [tudor199/Web3Arbitrage#5]
hi i hot errors 
Fail with error 'UniswapV2: TRANSFER_FAILED'
UniswapV2: INSUFFICIENT_INPUT_AMOUNT

why i got fail transaction with above errors is thare any solutions

**Comment by tudor199** [comment]
I advise you to check [uniswap documentation]( https://docs.uniswap.org/protocol/V2/introduction) for this problem.
