### ISSUE TITLE
suggition for more progitable

### ISSUE THREAD

**Issue by gsngsn123** [tudor199/Web3Arbitrage#6]
hi i learnt alot from ur repo finally ran after 1 one month got an idea but i cont implement in my research lot bots excuting 80% oppurtunity only .

i think this is possible and we can reduce failure transactions cause in one month my highest sucussfull transaction is $0.04 all remianing 2000 transactions are failure because of  (Fail with error 'ArbitrageExecutor: Initial check failed!')

**Comment by tudor199** [comment]
Hi! 
'ArbitrageExecutor: Initial check failed!' Means that the arbitrage is no longer available, someone took it already.
I am open for suggestions if you have any.

**Comment by gsngsn123** [comment]
yeah but why we very slow others even 3000 gas price and own node any other solutions to fast
