### ISSUE TITLE
'r': Percent of the amount after fees (float)

### ISSUE THREAD

**Issue by gsngsn123** [tudor199/Web3Arbitrage#7]
hi how can change it when change transaction fail with 'uniswapv2 K'

**Comment by tudor199** [comment]
Hi!
As you might have already guess, 'r' parameter for that particular router is not set accordingly, or perhaps the token you are trying to arbitrage with is a deflationary token, and might have some issues.
Basically, after you swap the tokens, for one pool the uniswap`s K constant is not the same before and after the swap.

**Comment by gsngsn123** [comment]
is thare any use to change r
