### ISSUE TITLE
about Web3Arbitrage

### ISSUE THREAD

**Issue by gsngsn123** [tudor199/Web3Arbitrage#8]
hi this is krishna from india iam your github follower and iam trying your web3arbitrage from the first i tried from own node also i cant generate profit more than $0.02 i just trying to make profit greater than transaction cost can pls help me cause iam very bad situation please please help me you can contract telegrame : @pamarthisaiwhatsapp : 917569592417and email : pamarthikrishnasai@gmail.com

**Comment by tudor199** [comment]
Hello!
This repository is for didactic purposes, if you really want to make it profitable, you must do what the others can`t and you must know what the others don`t know.
Someone who already know those things won`t make them public.
